# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# This pipeline syncs the local repo with the upstream GitHub repo.

schedules:
- cron: '00 6 * * *'
  displayName: Schedule mirror sync
  branches:
    include:
    - main
    - release/*
  always: true

# Disable PR and CI triggers.
pr: none
trigger: none

pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0
  displayName: 'Checkout Repository'

- powershell: |
    .\scripts\onebranch\sync-mirror.ps1 -FullBranchName $(Build.SourceBranch)
  env:
    AZDO_PAT: $(AZDO_PAT)
    User: $(Build.QueuedBy)
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Sync Mirror'
