# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# This workflow performs a build of the project and uploads the result as a build artifact.

parameters:
  # Name associated with the output of this build.
  - name: build_artifact
    type: string
  # Name of the job
  - name: name
    type: string
  # Additional options passed to msbuild.
  - name: build_options
    type: string
    default: ''
  - name: generate_release_package
    type: boolean
    default: false
  - name: build_codeql
    type: boolean
    default: false
  - name: build_msi
    type: boolean
    default: false
  - name: build_nuget
    type: boolean
    default: false
  - name: cxx_flags
    type: string
    default: ''
  - name: ld_flags
    type: string
    default: ''
  - name: configurations
    type: object
    default: ["Debug", "Release"]


jobs:
  - job: '${{parameters.name}}'
    timeoutInMinutes: 90

    strategy:
      matrix:
        ${{ each configuration in parameters.configurations }}:
          ${{ configuration }}:
            buildConfiguration: ${{ configuration }}

    pool:
      vmImage: 'windows-2022'
      type: windows

    variables:
      # Path to the solution file relative to the root of the project.
      SOLUTION_FILE_PATH: ebpf-for-windows.sln
      BUILD_ARTIFACT_NAME: ${{parameters.build_artifact}}
      BUILD_CONFIGURATION: $(buildConfiguration)
      BUILD_PLATFORM: x64
      BUILD_OPTIONS: ${{parameters.build_options}}
      CXX_FLAGS: ${{parameters.cxx_flags}}
      LD_FLAGS: ${{parameters.ld_flags}}
      MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64'
      GDN_CODESIGN_TARGETDIRECTORY: '$(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)'

    steps:
      - script: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          echo "##vso[task.setvariable variable=msvc_tools_path;isOutput=true]%VCToolsInstallDir%"
          echo "##vso[task.setvariable variable=msvc_tools_version;isOutput=true]%VCToolsVersion%"
        name: msvc_variables
        displayName: 'Set MSVC Environment Variables'

      - powershell: |
          $value = "true"
          Write-Host "##vso[task.setvariable variable=ASAN_WIN_CONTINUE_ON_INTERCEPTION_FAILURE;]$value"
        workingDirectory: $(Build.SourcesDirectory)
        displayName: 'Set ASAN_WIN_CONTINUE_ON_INTERCEPTION_FAILURE'

      - checkout: self
        displayName: 'Checkout Repo'
        submodules: 'recursive'
        fetchDepth: 0

      - bash: |
          echo "*** All environment variables ***"
          env | sort
        workingDirectory: $(Build.SourcesDirectory)
        displayName: 'Dump Environment variables'

      - bash: |
          choco install -y llvm --version 11.0.1 --allow-downgrade
          echo '##vso[task.prependpath]C:\Program Files\LLVM\bin'
          choco install wixtoolset
        workingDirectory: $(Build.SourcesDirectory)
        displayName:  'Install tools'

      - powershell: |
          .\scripts\initialize_ebpf_repo.ps1
        workingDirectory: $(Build.SourcesDirectory)
        displayName: 'Configuring repo for first build'

      - script: |
          "$(MSBUILD_PATH)\msbuild.exe" /m /p:Configuration=$(BUILD_CONFIGURATION) /p:Platform=$(BUILD_PLATFORM) $(SOLUTION_FILE_PATH) $(BUILD_OPTIONS)
        workingDirectory: $(Build.SourcesDirectory)
        displayName: 'Build'

      - script: |
          copy "$(msvc_variables.msvc_tools_path)\bin\Hostx64\x64\clang*"" .
        workingDirectory: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)
        displayName: 'Copy LLVM libs for Fuzzing & Address Sanitizing'

      - powershell: |
          Invoke-WebRequest https://github.com/microsoft/ebpf-for-windows-demo/releases/download/v0.0.2/$(BUILD_PLATFORM)-Debug-cilium-xdp.zip -OutFile x64-$(BUILD_CONFIGURATION)-cilium-xdp.zip
        workingDirectory: $(Build.SourcesDirectory)
        condition: or(eq(variables.buildConfiguration, 'Debug'), eq(variables.buildConfiguration, 'NativeOnlyDebug'))
        displayName: 'Download demo Debug repository'

      - powershell: |
          Invoke-WebRequest https://github.com/microsoft/ebpf-for-windows-demo/releases/download/v0.0.2/$(BUILD_PLATFORM)-Release-cilium-xdp.zip -OutFile x64-$(BUILD_CONFIGURATION)-cilium-xdp.zip
        workingDirectory: $(Build.SourcesDirectory)
        condition: or(eq(variables.buildConfiguration, 'Release'), eq(variables.buildConfiguration, 'NativeOnlyRelease'))
        displayName: 'Download demo Release repository'

      - script: |
          tar -xf ..\..\x64-$(BUILD_CONFIGURATION)-cilium-xdp.zip
        workingDirectory: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)
        condition: ne(variables.buildConfiguration, 'FuzzerDebug')
        displayName: 'Extract artifacts to build path'

      - publish: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)
        artifact: "${{parameters.build_artifact}} $(buildConfiguration)"
        displayName: 'Upload Build Output'

      - publish: $(Build.SourcesDirectory)/$(BUILD_PLATFORM)/$(buildConfiguration)/ebpf-for-windows.msi
        artifact: "ebpf-for-windows - MSI installer (${{parameters.build_artifact}}_$(buildConfiguration))"
        condition: and(eq('${{parameters.build_msi}}', 'true'), ne(variables.buildConfiguration, 'FuzzerDebug'))
        displayName: 'Upload the MSI package'

      - script: |
          "$(MSBUILD_PATH)\msbuild.exe" /m /p:Configuration="$(BUILD_CONFIGURATION)" /p:Platform="$(BUILD_PLATFORM)" "$(SOLUTION_FILE_PATH)" "$(BUILD_OPTIONS)" /t:tools\nuget
        condition: and(eq(variables.buildConfiguration, 'Release'), eq('${{parameters.build_nuget}}', 'true'))
        workingDirectory: $(Build.SourcesDirectory)
        displayName: 'Build the NuGet package'

      - bash: |
          echo "##vso[task.setvariable variable=REL_NUGET_PACKAGE_PATH;isOutput=true]$(ls $(BUILD_PLATFORM)/$(BUILD_CONFIGURATION)/*.nupkg)"
        condition: and(eq(variables.buildConfiguration, 'Release'), eq('${{parameters.build_nuget}}', 'true'))
        name: nuget_packages
        displayName: 'Locate the nuget package'

      - publish: $(nuget_packages.REL_NUGET_PACKAGE_PATH)
        artifact: 'ebpf-for-windows nuget'
        condition: and(eq(variables.buildConfiguration, 'Release'), eq('${{parameters.build_nuget}}', 'true'), eq('${{parameters.build_artifact}}', 'Build-x64'))
        displayName: 'Upload the nuget package'

      - publish: $(nuget_packages.REL_NUGET_PACKAGE_PATH)
        artifact: 'ebpf-for-windows-native nuget'
        condition: and(eq(variables.buildConfiguration, 'Release'), eq('${{parameters.build_nuget}}', 'true'), eq('${{parameters.build_artifact}}', 'Build-x64-native-only'))
        displayName: 'Upload the nuget package'
